export interface VaultStatus {
  enrolled: boolean
  network: string
  clientOrigin: string
  rpId: string
  vaultId: string
  templateVersion: string
  policyVersion: string
  operationalCsvBlocks: number
  savingsCsvBlocks: number
  externalOwnerWalletPub?: string
  vaultCosignerBasePub?: string
  arkadeCosignerBasePub?: string
  arkadeCosignerOrigin?: string
  arkadeCosignerVersion?: string
  operationalAddress: string
  operationalScript?: string
  savingsAddress: string
  savingsExcludesRoutineCosigners: boolean
  periodAllowance: number
  periodSpent: number
  periodRemaining: number
  txCap: number
  absoluteFeeCap: number
  feerateCapSatVb: number
  phoneRoutineBip340Pub?: string
  phoneDirectP256?: string
  tweakedVaultCosignerXOnly?: string
  tweakedArkadeCosignerXOnly?: string
  enrollmentMode?: string
  passkeyLoginAvailable?: boolean
  savingsScript?: string
  recoveryPub?: string
  recoveryKeyPub?: string
  warnings?: string[]
  vtxoVaultCosignerPub?: string
  vtxoExitDelay?: number
  vtxoExitDelayUnit?: string
  spendingArkAddress?: string
  spendingArkScript?: string
  spendingOnchainAddress?: string
  spendingOnchainScript?: string
  vtxoDelegatePub?: string
  vtxoBoardingActive?: boolean
  vtxoBoardingProgram?: string
  vtxoBoardingAddress?: string
  vtxoBoardingScript?: string
  vtxoBoardingExitDelay?: number
  vtxoBoardingExitDelayUnit?: string
}
